// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxwkKA51K0fZsj79lS3LQU41Z3LRzojnM',
    appId: '1:207415055154:web:d685e640eebf9fc5727d2b',
    messagingSenderId: '207415055154',
    projectId: 'nutriveda-7fbbc',
    authDomain: 'nutriveda-7fbbc.firebaseapp.com',
    storageBucket: 'nutriveda-7fbbc.firebasestorage.app',
    measurementId: 'G-T53BQT749S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3lgVPdVUlCJ9uoowWUJOQpT995dnCM8',
    appId: '1:207415055154:android:b80b36e11a89e22c727d2b',
    messagingSenderId: '207415055154',
    projectId: 'nutriveda-7fbbc',
    storageBucket: 'nutriveda-7fbbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvNkXJRv4OcZVxeTC30tzfB2_0VVOtITA',
    appId: '1:207415055154:ios:42fef1d4e7de8f97727d2b',
    messagingSenderId: '207415055154',
    projectId: 'nutriveda-7fbbc',
    storageBucket: 'nutriveda-7fbbc.firebasestorage.app',
    iosBundleId: 'com.example.nutriVeda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvNkXJRv4OcZVxeTC30tzfB2_0VVOtITA',
    appId: '1:207415055154:ios:42fef1d4e7de8f97727d2b',
    messagingSenderId: '207415055154',
    projectId: 'nutriveda-7fbbc',
    storageBucket: 'nutriveda-7fbbc.firebasestorage.app',
    iosBundleId: 'com.example.nutriVeda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxwkKA51K0fZsj79lS3LQU41Z3LRzojnM',
    appId: '1:207415055154:web:d779f9aae2589e8f727d2b',
    messagingSenderId: '207415055154',
    projectId: 'nutriveda-7fbbc',
    authDomain: 'nutriveda-7fbbc.firebaseapp.com',
    storageBucket: 'nutriveda-7fbbc.firebasestorage.app',
    measurementId: 'G-QCY30E60D2',
  );
}
